# agy (Gemini CLI) autonomous-profile renderer
#
# Pure function producing the config file contents baked into agent
# container images (dryvist/nix-agent-sandbox). Deliberately NOT a
# home-manager module: there must be no code path that renders these onto a
# host filesystem. Safety in this profile comes from the container boundary,
# scoped credentials, and default-deny egress.
#
# pkgs-free on purpose: image builders call this from evaluation contexts
# that have no nixpkgs instance, which is why the Policy Engine TOML is
# hand-rendered instead of going through pkgs.formats.toml.
#
# The product/repo is `agy`; the CLI binary is `gemini`, so the emitted
# paths stay `.gemini/`.
{
  lib,
  homeDir ? "/home/agent",
  residualDeny,
}:

let
  geminiPolicyPath = "${homeDir}/.gemini/policies/autonomous.toml";

  # Deny message for blocked commands (Gemini Policy Engine).
  geminiDenyMsg = "Command permanently blocked by security policy.";

  denyRules = map (cmd: {
    toolName = "run_shell_command";
    commandPrefix = cmd;
    decision = "deny";
    priority = 200;
    denyMessage = geminiDenyMsg;
  }) residualDeny;

  # JSON string literals are valid TOML strings; numbers render bare.
  tomlStr = builtins.toJSON;
  renderGeminiRule = rule: ''
    [[rule]]
    toolName = ${tomlStr rule.toolName}
    commandPrefix = ${tomlStr rule.commandPrefix}
    decision = ${tomlStr rule.decision}
    priority = ${toString rule.priority}
    denyMessage = ${tomlStr rule.denyMessage}
  '';

  # ~/.gemini/settings.json inside the image: approval mode under `general`,
  # Policy Engine TOML referenced via `policyPaths`. Gemini's own container
  # sandbox is disabled — we are already inside one. The yolo posture is
  # reinforced at launch (`gemini --approval-mode yolo`).
  geminiSettingsJson = builtins.toJSON {
    "$schema" =
      "https://raw.githubusercontent.com/google-gemini/gemini-cli/main/schemas/settings.schema.json";
    policyPaths = [ geminiPolicyPath ];
    general = {
      defaultApprovalMode = "yolo";
    };
    tools = {
      sandbox = false;
    };
  };

  # Policy Engine TOML: deny rules (priority 200) override yolo approval,
  # so the residual deny holds even in fully-autonomous mode.
  geminiPolicyToml = ''
    # Generated by nix-ai (autonomous profile).
  ''
  + lib.concatMapStrings renderGeminiRule denyRules;
in
{
  inherit residualDeny geminiSettingsJson geminiPolicyToml;

  # Home-relative path -> contents, ready for an image builder to bake
  # under ${homeDir}. One attrset so image builds cannot forget a file.
  files = {
    ".gemini/settings.json" = geminiSettingsJson;
    ".gemini/policies/autonomous.toml" = geminiPolicyToml;
  };
}
